//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAssemblies
    {
        public string jmaJobID { get; set; }
        public int jmaJobAssemblyID { get; set; }
        public decimal jmaLevel { get; set; }
        public int jmaParentAssemblyID { get; set; }
        public string jmaSourceMethodID { get; set; }
        public string jmaSourceRevisionID { get; set; }
        public string jmaPartID { get; set; }
        public string jmaPartRevisionID { get; set; }
        public string jmaPartWareHouseLocationID { get; set; }
        public string jmaPartBinID { get; set; }
        public string jmaUnitOfMeasure { get; set; }
        public string jmaPartShortDescription { get; set; }
        public decimal jmaQuantityPerParent { get; set; }
        public decimal jmaOrderQuantity { get; set; }
        public decimal jmaEstimatedUnitCost { get; set; }
        public decimal jmaInventoryQuantity { get; set; }
        public decimal jmaScrapQuantity { get; set; }
        public decimal jmaQuantityReceivedToInventory { get; set; }
        public decimal jmaScheduledStartHour { get; set; }
        public decimal jmaReceivedComplete { get; set; }
        public decimal jmaScheduledDueHour { get; set; }
        public decimal jmaProductionQuantity { get; set; }
        public decimal jmaQuantityToMake { get; set; }
        public decimal jmaQuantityToPull { get; set; }
        public decimal jmaQuantityIssued { get; set; }
        public decimal jmaPullAllFromStock { get; set; }
        public decimal jmaIssuedComplete { get; set; }
        public Nullable<System.DateTime> jmaScheduledStartDate { get; set; }
        public Nullable<System.DateTime> jmaScheduledDueDate { get; set; }
        public int jmaOverlapJobOperationID { get; set; }
        public decimal jmaOverlapType { get; set; }
        public decimal jmaProductionComplete { get; set; }
        public decimal jmaQuantityCompleted { get; set; }
        public Nullable<System.DateTime> jmaCompletedDate { get; set; }
        public decimal jmaClosed { get; set; }
        public string jmaCreatedBy { get; set; }
        public Nullable<System.DateTime> jmaCreatedDate { get; set; }
        public System.Guid jmaUniqueID { get; set; }
        public string jmaPartLongDescriptionRTF { get; set; }
        public string jmaPartLongDescriptionText { get; set; }
        public string jmaProductionNotesRTF { get; set; }
        public string jmaProductionNotesText { get; set; }
        public string jmaDocuments { get; set; }
        public decimal jmaScrapQuantityCompleted { get; set; }
        public string UJMAMATERIALOFCONSTRUCTION { get; set; }
        public string UJMAITEMNO { get; set; }
    }
}
