//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizations
    {
        public string cmoOrganizationID { get; set; }
        public string cmoName { get; set; }
        public string cmoAddressLine1 { get; set; }
        public string cmoAddressLine2 { get; set; }
        public string cmoAddressLine3 { get; set; }
        public string cmoCity { get; set; }
        public string cmoCounty { get; set; }
        public string cmoState { get; set; }
        public string cmoPostCode { get; set; }
        public string cmoCountry { get; set; }
        public string cmoPhoneNumber { get; set; }
        public string cmoAlternatePhoneNumber { get; set; }
        public string cmoFaxNumber { get; set; }
        public string cmoWebAddress { get; set; }
        public string cmoOrganizationAccountID { get; set; }
        public string cmoARInvoiceContactID { get; set; }
        public string cmoQuoteContactID { get; set; }
        public string cmoShipContactID { get; set; }
        public string cmoPurchaseContactID { get; set; }
        public Nullable<System.DateTime> cmoEstablishedDate { get; set; }
        public string cmoAPInvoiceContactID { get; set; }
        public decimal cmoPrintStatement { get; set; }
        public decimal cmoEmployeeCount { get; set; }
        public decimal cmoCompetitor { get; set; }
        public decimal cmoFinanceCompany { get; set; }
        public decimal cmoCustomerStatus { get; set; }
        public Nullable<System.DateTime> cmoCustomerProspectDate { get; set; }
        public Nullable<System.DateTime> cmoCustomerActiveDate { get; set; }
        public Nullable<System.DateTime> cmoCustomerInactiveDate { get; set; }
        public decimal cmoSupplierStatus { get; set; }
        public Nullable<System.DateTime> cmoSupplierProspectDate { get; set; }
        public Nullable<System.DateTime> cmoSupplierActiveDate { get; set; }
        public Nullable<System.DateTime> cmoSupplierInactiveDate { get; set; }
        public decimal cmoRequires1099 { get; set; }
        public string cmoSupplierPaymentTermID { get; set; }
        public string cmoSupplierShippingMethodID { get; set; }
        public decimal cmoSupplierTaxable { get; set; }
        public string cmoSupplierTaxCodeID { get; set; }
        public string cmoSupplierSecondTaxCodeID { get; set; }
        public string cmoAccountManagerEmployeeID { get; set; }
        public string cmoCustomerGroupID { get; set; }
        public decimal cmoCustomerTaxable { get; set; }
        public string cmoCustomerTaxCodeID { get; set; }
        public string cmoCustomerSecondTaxCodeID { get; set; }
        public string cmoCustomerPaymentTermsID { get; set; }
        public decimal cmoCalculateFinanceCharges { get; set; }
        public decimal cmoIncludeFreightInPrice { get; set; }
        public string cmoCurrencyRateID { get; set; }
        public decimal cmoCreditHold { get; set; }
        public decimal cmoCustomerCreditLimit { get; set; }
        public string cmoDefaultQuoteLocationID { get; set; }
        public string cmoDefaultShipLocationID { get; set; }
        public string cmoDefaultARInvoiceLocationID { get; set; }
        public string cmoDefaultPurchaseLocationID { get; set; }
        public string cmoDefaultAPInvoiceLocationID { get; set; }
        public string cmoDropShipOrganizationID { get; set; }
        public string cmoDropShipLocationID { get; set; }
        public string cmoEFTDescription { get; set; }
        public string cmoTaxExemptNumber { get; set; }
        public string cmoFederalID { get; set; }
        public decimal cmoDirectPayment { get; set; }
        public string cmoBankInitials { get; set; }
        public string cmoBSBNumber { get; set; }
        public string cmoBankAccountName { get; set; }
        public string cmoBankAccountNumber { get; set; }
        public string cmoNonTaxReasonID { get; set; }
        public string cmoCustomerShippingMethodID { get; set; }
        public string cmoCustomerShipPaymentTypeID { get; set; }
        public decimal cmoJobPriorityID { get; set; }
        public decimal cmoARInvoicePerShipmentLine { get; set; }
        public decimal cmoCreatedFromWeb { get; set; }
        public decimal cmoResellerStatus { get; set; }
        public Nullable<System.DateTime> cmoResellerProspectDate { get; set; }
        public Nullable<System.DateTime> cmoResellerActiveDate { get; set; }
        public Nullable<System.DateTime> cmoResellerInactiveDate { get; set; }
        public string cmoResellerOrganizationID { get; set; }
        public string cmoResellerLocationID { get; set; }
        public string cmoResellerContactID { get; set; }
        public decimal cmoResellerCommissionRate { get; set; }
        public string cmoUPSAcctNumber { get; set; }
        public decimal cmoRequiresInspection { get; set; }
        public string cmoUPSBillingOption { get; set; }
        public decimal cmoResidentialAddress { get; set; }
        public decimal cmoSupplierAccredited { get; set; }
        public Nullable<System.DateTime> cmoSupplierAccreditedDate { get; set; }
        public string cmoSupplierRatingID { get; set; }
        public string cmoBankAccountType { get; set; }
        public string cmoCreatedBy { get; set; }
        public Nullable<System.DateTime> cmoCreatedDate { get; set; }
        public System.Guid cmoUniqueID { get; set; }
        public string cmoEMailAddress { get; set; }
        public string cmoLongDescriptionRTF { get; set; }
        public string cmoLongDescriptionText { get; set; }
        public string cmoAttachmentFileFolder { get; set; }
        public decimal UCMOCONSULTANT { get; set; }
        public string UCMOTELEXT { get; set; }
        public string cmoCountryCode { get; set; }
        public string UCMOACCTGMEMO { get; set; }
        public Nullable<System.DateTime> UCMOACORDEXPDATE { get; set; }
        public decimal UCMOFORMW9 { get; set; }
        public string UCMOFIN { get; set; }
        public string cmoHDAttachmentFilePath { get; set; }
        public string cmoFreeOnBoardDescription { get; set; }
        public decimal cmoAPIncludeTaxInRetention { get; set; }
        public decimal cmoARIncludeTaxInRetention { get; set; }
        public string cmoUPS3rdPartyOrganizationID { get; set; }
        public string cmoUPS3rdPartyLocationID { get; set; }
        public decimal UCMOSIC { get; set; }
        public string UCMOADVERTISING_SOURCE_ID { get; set; }
        public decimal UCMOSTANDARDIZED_FLAG { get; set; }
        public decimal UCMOENDUSER { get; set; }
        public decimal cmoForm1099Box { get; set; }
        public string cmoEFTCode { get; set; }
        public string cmoEFTParticulars { get; set; }
        public decimal UCMOLIST_ONLY_FLAG { get; set; }
        public string UCMOSHIPCONFIRMATIONEMAIL { get; set; }
        public decimal UCMOPARTSCOMMISSIONPCT { get; set; }
        public decimal UCMOSALESTOTAL { get; set; }
    }
}
