//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationContacts
    {
        public string cmcOrganizationID { get; set; }
        public string cmcLocationID { get; set; }
        public string cmcContactID { get; set; }
        public string cmcContactTitleID { get; set; }
        public string cmcName { get; set; }
        public string cmcPhoneNumber { get; set; }
        public string cmcAlternatePhoneNumber { get; set; }
        public string cmcMobileNumber { get; set; }
        public string cmcFaxNumber { get; set; }
        public decimal cmcWebLoginEnabled { get; set; }
        public string cmcWebUserID { get; set; }
        public string cmcWebPassword { get; set; }
        public string cmcWebTemplate { get; set; }
        public Nullable<System.DateTime> cmcWebExpirationDate { get; set; }
        public decimal cmcNoMailings { get; set; }
        public string cmcCorrespondenceMethod { get; set; }
        public decimal cmcInactive { get; set; }
        public Nullable<System.DateTime> cmcInactiveDate { get; set; }
        public string cmcCreatedBy { get; set; }
        public Nullable<System.DateTime> cmcCreatedDate { get; set; }
        public System.Guid cmcUniqueID { get; set; }
        public string cmcEMailAddress { get; set; }
        public string cmcNoteRTF { get; set; }
        public string cmcNoteText { get; set; }
        public string UCMCTELEXT { get; set; }
        public string UCMCFIRST { get; set; }
        public string UCMCLAST { get; set; }
        public decimal UCMCLEAD { get; set; }
        public decimal UCMCEMAIL_BAD_FLAG { get; set; }
        public Nullable<System.DateTime> UCMCCONTACTUPDATE { get; set; }
        public int UCMCLETTERTEMPLATEID { get; set; }
        public decimal UCMCLOYALTYMEMBER { get; set; }
        public string UCMCORDERIDREFERENCE { get; set; }
        public decimal UCMCREPREPORTEMAILOPTOUT { get; set; }
    }
}
