//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartClasses
    {
        public string imcPartClassID { get; set; }
        public string imcDescription { get; set; }
        public decimal imcShowGroupOnWeb { get; set; }
        public string imcPartImageFileName { get; set; }
        public string imcParentPartClassID { get; set; }
        public decimal imcRequiresInspection { get; set; }
        public decimal imcWebConfigPriceRule { get; set; }
        public decimal imcWebConfigMode { get; set; }
        public string imcFdxPackaging { get; set; }
        public decimal imcWeight { get; set; }
        public decimal imcFdxOneItemPerShipment { get; set; }
        public decimal imcFdxNonstandardContainer { get; set; }
        public int imcFdxPackageLength { get; set; }
        public int imcFdxPackageWidth { get; set; }
        public int imcFdxPackageHeight { get; set; }
        public decimal imcFdxHandlingCost { get; set; }
        public decimal imcFdxPackagingCost { get; set; }
        public decimal imcFdxShipCostMarkupPct { get; set; }
        public string imcCreatedBy { get; set; }
        public decimal imcInactive { get; set; }
        public Nullable<System.DateTime> imcInactiveDate { get; set; }
        public Nullable<System.DateTime> imcCreatedDate { get; set; }
        public System.Guid imcUniqueID { get; set; }
        public string imcInventoryGLAccountID { get; set; }
    }
}
