//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public string impPartID { get; set; }
        public string impShortDescription { get; set; }
        public decimal impPartType { get; set; }
        public string impPartGroupID { get; set; }
        public string impPartClassID { get; set; }
        public string impCycleCodeID { get; set; }
        public string impOEMOrganizationID { get; set; }
        public decimal impNonStockedItem { get; set; }
        public decimal impWebSellableToAll { get; set; }
        public decimal impAlwaysNonTaxable { get; set; }
        public string impTaxCodeID { get; set; }
        public string impSecondTaxCodeID { get; set; }
        public string impNonTaxReasonID { get; set; }
        public decimal impContractLength { get; set; }
        public string impContractLengthType { get; set; }
        public decimal impDeliveryType { get; set; }
        public decimal impTrackSerialNumbers { get; set; }
        public decimal impTrackLotNumbers { get; set; }
        public decimal impNonPhysicalShipment { get; set; }
        public decimal impPhantomOrKitPart { get; set; }
        public decimal impBuyForInventory { get; set; }
        public decimal impInactive { get; set; }
        public Nullable<System.DateTime> impInactiveDate { get; set; }
        public string impCreatedBy { get; set; }
        public Nullable<System.DateTime> impCreatedDate { get; set; }
        public System.Guid impUniqueID { get; set; }
        public decimal UIMPASSEMBLY { get; set; }
        public string impLongDescriptionRTF { get; set; }
        public string impLongDescriptionText { get; set; }
        public string impNextSerialNumberIDFormula { get; set; }
    }
}
