//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderLines
    {
        public string omlSalesOrderID { get; set; }
        public decimal omlSalesOrderLineID { get; set; }
        public string omlPartID { get; set; }
        public string omlOrgPartID { get; set; }
        public string omlPartRevisionID { get; set; }
        public string omlUnitOfMeasure { get; set; }
        public string omlPartGroupID { get; set; }
        public string omlPartShortDescription { get; set; }
        public string omlOrgPartShortDescription { get; set; }
        public decimal omlOrderQuantity { get; set; }
        public decimal omlFullUnitPriceBase { get; set; }
        public decimal omlFullUnitPriceForeign { get; set; }
        public decimal omlDiscountPercent { get; set; }
        public decimal omlUnitDiscountBase { get; set; }
        public decimal omlUnitDiscountForeign { get; set; }
        public decimal omlUnitPriceBase { get; set; }
        public decimal omlUnitPriceForeign { get; set; }
        public decimal omlFullExtendedPriceBase { get; set; }
        public decimal omlFullExtendedPriceForeign { get; set; }
        public decimal omlExtendedDiscountBase { get; set; }
        public decimal omlExtendedDiscountForeign { get; set; }
        public decimal omlExtendedPriceBase { get; set; }
        public decimal omlExtendedPriceForeign { get; set; }
        public decimal omlFreightAmountBase { get; set; }
        public decimal omlFreightAmountForeign { get; set; }
        public string omlTaxCodeID { get; set; }
        public string omlNonTaxReasonID { get; set; }
        public decimal omlTaxAmountBase { get; set; }
        public decimal omlTaxAmountForeign { get; set; }
        public string omlSecondTaxCodeID { get; set; }
        public decimal omlSecondTaxAmountBase { get; set; }
        public decimal omlSecondTaxAmountForeign { get; set; }
        public decimal omlPayCommission { get; set; }
        public decimal omlTimeAndMaterial { get; set; }
        public decimal omlQuantityShipped { get; set; }
        public string omlQuoteID { get; set; }
        public decimal omlQuoteLineID { get; set; }
        public decimal omlQuoteQuantityID { get; set; }
        public string omlLeadID { get; set; }
        public decimal omlLeadLineID { get; set; }
        public string omlRMAClaimID { get; set; }
        public decimal omlRMAClaimLineID { get; set; }
        public decimal omlConfigured { get; set; }
        public string omlProjectID { get; set; }
        public string omlProjectAreaID { get; set; }
        public decimal omlWeight { get; set; }
        public string omlPOSSessionID { get; set; }
        public string omlPOSTransactionID { get; set; }
        public decimal omlPOSTransactionLineID { get; set; }
        public decimal omlClosed { get; set; }
        public decimal omlPriceOverride { get; set; }
        public string omlCreatedBy { get; set; }
        public Nullable<System.DateTime> omlCreatedDate { get; set; }
        public System.Guid omlUniqueID { get; set; }
        public decimal omlDeposit { get; set; }
        public decimal omlDepositPercent { get; set; }
        public decimal omlDepositAmountBase { get; set; }
        public decimal omlDepositAmountForeign { get; set; }
        public decimal omlDepositCreated { get; set; }
        public decimal omlDepositCredited { get; set; }
        public decimal UOMLSTARTUPCOST { get; set; }
        public string UOMLRESELLERID { get; set; }
        public string UOMLINPUTSIZE { get; set; }
        public string UOMLMATL { get; set; }
        public string UOMLQMIN { get; set; }
        public string UOMLQAVG { get; set; }
        public string UOMLQMAX { get; set; }
        public string UOMLOUTPUTSIZE { get; set; }
        public string UOMLCONSULTANTID { get; set; }
        public string UOMLSERIALNUMBER { get; set; }
        public string UOMLENDUSERID { get; set; }
        public string UOMLPARTCLASSID { get; set; }
        public string UOMLMODEL { get; set; }
        public string UOMLMMFG { get; set; }
        public string UOMLMPHASE { get; set; }
        public string UOMLMSPECIAL { get; set; }
        public string UOMLSPEC { get; set; }
        public string UOMLMFRAME { get; set; }
        public string UOMLMENC { get; set; }
        public string UOMLMATERIALOFCONSTRUCTION { get; set; }
        public string UOMLMHP { get; set; }
        public string omlPartLongDescriptionRTF { get; set; }
        public string omlPartLongDescriptionText { get; set; }
        public string UOMLQUOTETEXTTEXT { get; set; }
        public string UOMLQUOTETEXTRTF { get; set; }
        public string UOMLMHERTZ { get; set; }
        public string UOMLMVOLTS { get; set; }
        public string UOMLMRPM { get; set; }
        public string UOMLLOCATIONID { get; set; }
        public string UOMLENDUSERCONTACTID { get; set; }
        public decimal UOMLPAYCOMMISSION { get; set; }
        public decimal UOMLCOSTADJUST { get; set; }
        public string UOMLCOSTADJUSTREASON { get; set; }
        public string UOMLJOBNEEDS { get; set; }
        public decimal UOMLSTANDARDLABORCOST { get; set; }
        public decimal UOMLSTANDARDSUBCONTRACTCOST { get; set; }
        public decimal UOMLSTANDARDMATERIALCOST { get; set; }
        public decimal UOMLSTANDARDOVERHEADCOST { get; set; }
        public string UOMLSALESORDERID { get; set; }
        public string omlDocuments { get; set; }
        public decimal UOMLDONOTPRINTTHISLINE { get; set; }
        public string UOMLFMI_ENGINEER { get; set; }
        public Nullable<System.DateTime> UOMLSTARTUP_DATE { get; set; }
        public Nullable<System.DateTime> UOMLSTDMATCOSTDATE { get; set; }
        public decimal UOMLSCOPEOFSUPPLYPRINT { get; set; }
        public decimal UOMLSTANDARDCOSTFLAG { get; set; }
    }
}
