//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrders
    {
        public string ompSalesOrderID { get; set; }
        public string ompPlantID { get; set; }
        public string ompPlantDepartmentID { get; set; }
        public string ompCustomerOrganizationID { get; set; }
        public string ompARInvoiceLocationID { get; set; }
        public string ompARInvoiceContactID { get; set; }
        public string ompQuoteLocationID { get; set; }
        public string ompQuoteContactID { get; set; }
        public string ompShipOrganizationID { get; set; }
        public string ompShipLocationID { get; set; }
        public string ompShipContactID { get; set; }
        public string ompCustomerPO { get; set; }
        public Nullable<System.DateTime> ompRequestedShipDate { get; set; }
        public Nullable<System.DateTime> ompOrderDate { get; set; }
        public string ompFreeOnBoardDescription { get; set; }
        public string ompShippingMethodID { get; set; }
        public string ompShippingPaymentTypeID { get; set; }
        public string ompPaymentTermID { get; set; }
        public string ompResellerOrganizationID { get; set; }
        public string ompResellerLocationID { get; set; }
        public string ompResellerContactID { get; set; }
        public decimal ompCreatedFromWeb { get; set; }
        public decimal ompReadyToPrint { get; set; }
        public string ompStandardMessageID { get; set; }
        public string ompCurrencyRateID { get; set; }
        public decimal ompCustomRate { get; set; }
        public decimal ompExchangeRate { get; set; }
        public decimal ompFullOrderSubtotalBase { get; set; }
        public decimal ompFullOrderSubtotalForeign { get; set; }
        public decimal ompDiscountTotalBase { get; set; }
        public decimal ompDiscountTotalForeign { get; set; }
        public decimal ompOrderSubtotalBase { get; set; }
        public decimal ompOrderSubTotalForeign { get; set; }
        public decimal ompFreightSubtotalBase { get; set; }
        public decimal ompFreightSubtotalForeign { get; set; }
        public decimal ompTotalOrderWeight { get; set; }
        public decimal ompFreightAmountBase { get; set; }
        public decimal ompFreightAmountForeign { get; set; }
        public decimal ompFreightTotalBase { get; set; }
        public decimal ompFreightTotalForeign { get; set; }
        public string ompFreightTaxCodeID { get; set; }
        public decimal ompFreightTaxAmountBase { get; set; }
        public decimal ompFreightTaxAmountForeign { get; set; }
        public string ompSecondFreightTaxCodeID { get; set; }
        public decimal ompSecondFreightTaxAmtBase { get; set; }
        public decimal ompSecondFreightTaxAmtForeign { get; set; }
        public decimal ompOrderTaxAmountBase { get; set; }
        public decimal ompOrderTaxAmountForeign { get; set; }
        public decimal ompOrderTotalBase { get; set; }
        public decimal ompOrderTotalForeign { get; set; }
        public decimal ompStatus { get; set; }
        public Nullable<System.DateTime> ompApprovalRequestDate { get; set; }
        public Nullable<System.DateTime> ompApprovalDecisionDate { get; set; }
        public string ompNextApprovalEmployeeID { get; set; }
        public string ompProjectID { get; set; }
        public decimal ompClosed { get; set; }
        public Nullable<System.DateTime> ompClosedDate { get; set; }
        public string ompCreatedBy { get; set; }
        public Nullable<System.DateTime> ompCreatedDate { get; set; }
        public System.Guid ompUniqueID { get; set; }
        public decimal ompDeposit { get; set; }
        public decimal ompDepositPercent { get; set; }
        public decimal ompDepositAmountBase { get; set; }
        public decimal ompDepositAmountForeign { get; set; }
        public decimal ompDepositCreated { get; set; }
        public string UOMPCONSULTANTID { get; set; }
        public string UOMPCONTACTTITLEID { get; set; }
        public string UOMPINDUSTRYTYPEID { get; set; }
        public string UOMPSERIALNUMBER { get; set; }
        public decimal UOMPSUBMIT { get; set; }
        public string ompOrderCommentsRTF { get; set; }
        public string ompOrderCommentsText { get; set; }
        public string UOMPCLOCATIONID { get; set; }
        public string UOMPCMBOMPQUOTECONTACTTITLE { get; set; }
        public string UOMPCMBOMPSHIPCONTACTTITLE { get; set; }
        public string UOMPCONSULTANTCONTACTID { get; set; }
        public string ompCallID { get; set; }
        public string UOMPRESELLER2ID { get; set; }
        public decimal UOMPCOMPERCENT { get; set; }
        public decimal UOMPCOMADJUSTMENT { get; set; }
        public decimal UOMPFREIGHTAMOUNTBASE { get; set; }
        public string UOMPCOMADJREASON { get; set; }
        public decimal UOMPREP1SPLIT { get; set; }
        public decimal UOMPREP2SPLIT { get; set; }
        public string UOMPSTATUSNOTES { get; set; }
        public decimal UOMPSETCOMMISSION { get; set; }
        public Nullable<System.DateTime> UOMPPRODSCHDATE { get; set; }
        public string UOMPSUBQTY { get; set; }
        public string UOMPENGINEERINGSCHEDULE { get; set; }
        public string UOMPFMI_ENGINEER { get; set; }
        public Nullable<System.DateTime> UOMPAPPROVEDATE { get; set; }
        public decimal UOMPFULLAPPROVAL { get; set; }
        public string UOMPSHIPBY { get; set; }
        public decimal UOMPSUBMITTALS { get; set; }
        public string UOMPWARRANTY_TEXT { get; set; }
        public int UOMPWARRANTY_SHIP_MONTHS { get; set; }
        public int UOMPWARRANTY_STARTUP_MONTHS { get; set; }
        public decimal UOMPAPPROVEDBYLEGAL { get; set; }
        public Nullable<System.DateTime> UOMPPRODSHIPDATE { get; set; }
        public decimal UOMPOMDONE { get; set; }
        public string UOMPPROJECT { get; set; }
        public decimal UOMPSUBMITTALSENT { get; set; }
        public Nullable<System.DateTime> UOMPSUBMITTALFOLLOWUPDATE { get; set; }
        public string UOMPORDERREASONID { get; set; }
        public string UOMPORDERREASONNOTE { get; set; }
    }
}
