//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderSalesPeople
    {
        public string omiSalesOrderID { get; set; }
        public decimal omiSequenceID { get; set; }
        public string omiSalesEmployeeID { get; set; }
        public decimal omiClosed { get; set; }
        public string omiCreatedBy { get; set; }
        public Nullable<System.DateTime> omiCreatedDate { get; set; }
        public System.Guid omiUniqueID { get; set; }
        public decimal omiPercent { get; set; }
    }
}
