//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobMaterials
    {
        public string jmmJobID { get; set; }
        public int jmmJobAssemblyID { get; set; }
        public int jmmJobMaterialID { get; set; }
        public string jmmPartID { get; set; }
        public string jmmPartRevisionID { get; set; }
        public string jmmPartWarehouseLocationID { get; set; }
        public string jmmPartBinID { get; set; }
        public string jmmUnitOfMeasure { get; set; }
        public string jmmPartShortDescription { get; set; }
        public decimal jmmScrapPercent { get; set; }
        public decimal jmmScrapQuantity { get; set; }
        public decimal jmmEstimatedQuantity { get; set; }
        public decimal jmmEstimatedUnitCost { get; set; }
        public decimal jmmMinimumCharge { get; set; }
        public decimal jmmCalculatedUnitCost { get; set; }
        public decimal jmmKitPart { get; set; }
        public decimal jmmQuantityBreak1 { get; set; }
        public decimal jmmUnitCost1 { get; set; }
        public decimal jmmQuantityBreak2 { get; set; }
        public decimal jmmUnitCost2 { get; set; }
        public decimal jmmQuantityBreak3 { get; set; }
        public decimal jmmUnitCost3 { get; set; }
        public decimal jmmQuantityBreak4 { get; set; }
        public decimal jmmUnitCost4 { get; set; }
        public decimal jmmQuantityBreak5 { get; set; }
        public decimal jmmUnitCost5 { get; set; }
        public decimal jmmQuantityBreak6 { get; set; }
        public decimal jmmUnitCost6 { get; set; }
        public decimal jmmQuantityBreak7 { get; set; }
        public decimal jmmUnitCost7 { get; set; }
        public decimal jmmQuantityBreak8 { get; set; }
        public decimal jmmUnitCost8 { get; set; }
        public decimal jmmQuantityBreak9 { get; set; }
        public decimal jmmUnitCost9 { get; set; }
        public string jmmSupplierOrganizationID { get; set; }
        public string jmmPurchaseLocationID { get; set; }
        public decimal jmmFirm { get; set; }
        public string jmmPurchaseOrderID { get; set; }
        public decimal jmmLeadTime { get; set; }
        public Nullable<System.DateTime> jmmDueInDate { get; set; }
        public Nullable<System.DateTime> jmmRequiredDate { get; set; }
        public Nullable<System.DateTime> jmmOrderByDate { get; set; }
        public decimal jmmQuantityReceived { get; set; }
        public decimal jmmScrapQuantityReceived { get; set; }
        public decimal jmmReceivedComplete { get; set; }
        public int jmmRelatedJobOperationID { get; set; }
        public decimal jmmBackflush { get; set; }
        public decimal jmmClosed { get; set; }
        public decimal jmmQuantityToInspect { get; set; }
        public string jmmRFQID { get; set; }
        public string jmmCreatedBy { get; set; }
        public Nullable<System.DateTime> jmmCreatedDate { get; set; }
        public System.Guid jmmUniqueID { get; set; }
        public string jmmPartLongDescriptionRTF { get; set; }
        public string jmmPartLongDescriptionText { get; set; }
        public string jmmDocuments { get; set; }
        public decimal jmmQuantityPerAssembly { get; set; }
        public decimal UJMMNONSTANDARDPART { get; set; }
        public string UJMMITEMNO { get; set; }
        public string UJMMMATERIALOFCONSTRUCTION { get; set; }
    }
}
