//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOperations
    {
        public string jmoJobID { get; set; }
        public int jmoJobAssemblyID { get; set; }
        public int jmoJobOperationID { get; set; }
        public decimal jmoOperationType { get; set; }
        public decimal jmoAddedOperation { get; set; }
        public decimal jmoPrototypeOperation { get; set; }
        public string jmoPlantID { get; set; }
        public string jmoPlantDepartmentID { get; set; }
        public string jmoWorkCenterID { get; set; }
        public string jmoProcessID { get; set; }
        public string jmoProcessShortDescription { get; set; }
        public decimal jmoSetupHours { get; set; }
        public decimal jmoProductionStandard { get; set; }
        public string jmoStandardFactor { get; set; }
        public decimal jmoSetupRate { get; set; }
        public decimal jmoProductionRate { get; set; }
        public decimal jmoOverheadRate { get; set; }
        public decimal jmoOperationQuantity { get; set; }
        public decimal jmoQuantityComplete { get; set; }
        public decimal jmoSetupPercentComplete { get; set; }
        public decimal jmoActualSetupHours { get; set; }
        public decimal jmoActualProductionHours { get; set; }
        public decimal jmoSetupComplete { get; set; }
        public decimal jmoProductionComplete { get; set; }
        public decimal jmoOverlap { get; set; }
        public decimal jmoMachineType { get; set; }
        public decimal jmoWorkCenterMachineID { get; set; }
        public string jmoPartID { get; set; }
        public string jmoPartRevisionID { get; set; }
        public string jmoUnitOfMeasure { get; set; }
        public string jmoSupplierOrganizationID { get; set; }
        public string jmoPurchaseLocationID { get; set; }
        public decimal jmoFirm { get; set; }
        public string jmoPurchaseOrderID { get; set; }
        public decimal jmoEstimatedUnitCost { get; set; }
        public decimal jmoMinimumCharge { get; set; }
        public decimal jmoSetupCharge { get; set; }
        public decimal jmoCalculatedUnitCost { get; set; }
        public decimal jmoQuantityBreak1 { get; set; }
        public decimal jmoUnitCost1 { get; set; }
        public decimal jmoQuantityBreak2 { get; set; }
        public decimal jmoUnitCost2 { get; set; }
        public decimal jmoQuantityBreak3 { get; set; }
        public decimal jmoUnitCost3 { get; set; }
        public decimal jmoQuantityBreak4 { get; set; }
        public decimal jmoUnitCost4 { get; set; }
        public decimal jmoQuantityBreak5 { get; set; }
        public decimal jmoUnitCost5 { get; set; }
        public decimal jmoQuantityBreak6 { get; set; }
        public decimal jmoUnitCost6 { get; set; }
        public decimal jmoQuantityBreak7 { get; set; }
        public decimal jmoUnitCost7 { get; set; }
        public decimal jmoQuantityBreak8 { get; set; }
        public decimal jmoUnitCost8 { get; set; }
        public decimal jmoQuantityBreak9 { get; set; }
        public decimal jmoUnitCost9 { get; set; }
        public Nullable<System.DateTime> jmoStartDate { get; set; }
        public Nullable<System.DateTime> jmoDueDate { get; set; }
        public decimal jmoStartHour { get; set; }
        public decimal jmoDueHour { get; set; }
        public decimal jmoEstimatedProductionHours { get; set; }
        public decimal jmoCompletedSetupHours { get; set; }
        public decimal jmoCompletedProductionHours { get; set; }
        public decimal jmoClosed { get; set; }
        public decimal jmoInspectionComplete { get; set; }
        public decimal jmoInspectionStatus { get; set; }
        public decimal jmoInspectionType { get; set; }
        public string jmoRFQID { get; set; }
        public string jmoCreatedBy { get; set; }
        public Nullable<System.DateTime> jmoCreatedDate { get; set; }
        public System.Guid jmoUniqueID { get; set; }
        public string jmoProcessLongDescriptionRTF { get; set; }
        public string jmoProcessLongDescriptionText { get; set; }
        public string jmoDocuments { get; set; }
        public string jmoSFEMessageRTF { get; set; }
        public string jmoSFEMessageText { get; set; }
        public decimal jmoQuantityPerAssembly { get; set; }
        public decimal UJMOPRODUCTIONSTDTOTAL { get; set; }
    }
}
