//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public string jmpJobID { get; set; }
        public Nullable<System.DateTime> jmpProductionDueDate { get; set; }
        public string jmpPlantDepartmentID { get; set; }
        public string jmpPlantID { get; set; }
        public string jmpCustomerOrganizationID { get; set; }
        public Nullable<System.DateTime> jmpJobDate { get; set; }
        public string jmpPartID { get; set; }
        public string jmpPartRevisionID { get; set; }
        public string jmpPartWareHouseLocationID { get; set; }
        public string jmpPartBinID { get; set; }
        public string jmpUnitOfMeasure { get; set; }
        public string jmpPartShortDescription { get; set; }
        public decimal jmpOrderQuantity { get; set; }
        public decimal jmpInventoryQuantity { get; set; }
        public decimal jmpScrapQuantity { get; set; }
        public decimal jmpProductionQuantity { get; set; }
        public Nullable<System.DateTime> jmpScheduledStartDate { get; set; }
        public decimal jmpScheduledStartHour { get; set; }
        public Nullable<System.DateTime> jmpScheduledDueDate { get; set; }
        public decimal jmpScheduledDueHour { get; set; }
        public decimal jmpFirm { get; set; }
        public decimal jmpJobPriorityID { get; set; }
        public decimal jmpTimeAndMaterial { get; set; }
        public decimal jmpPlanningComplete { get; set; }
        public string jmpPlannerEmployeeID { get; set; }
        public decimal jmpScheduleComplete { get; set; }
        public decimal jmpScheduleLocked { get; set; }
        public decimal jmpReleasedToFloor { get; set; }
        public decimal jmpOnHold { get; set; }
        public decimal jmpReadyToPrint { get; set; }
        public decimal jmpProductionComplete { get; set; }
        public decimal jmpQuantityCompleted { get; set; }
        public Nullable<System.DateTime> jmpCompletedDate { get; set; }
        public decimal jmpQuantityShipped { get; set; }
        public decimal jmpQuantityReceivedToInventory { get; set; }
        public string jmpQuoteID { get; set; }
        public decimal jmpQuoteLineID { get; set; }
        public string jmpSourceMethodID { get; set; }
        public string jmpSourceRevisionID { get; set; }
        public string jmpRMAClaimID { get; set; }
        public decimal jmpRMAClaimLineID { get; set; }
        public decimal jmpRMAClaimProblemID { get; set; }
        public string jmpProjectID { get; set; }
        public decimal jmpClosed { get; set; }
        public Nullable<System.DateTime> jmpClosedDate { get; set; }
        public string jmpProjectAreaID { get; set; }
        public string jmpNonConformanceID { get; set; }
        public string jmpCreatedBy { get; set; }
        public Nullable<System.DateTime> jmpCreatedDate { get; set; }
        public System.Guid jmpUniqueID { get; set; }
        public decimal jmpScrapQuantityCompleted { get; set; }
        public string jmpCallID { get; set; }
        public string UJMPMPHASE { get; set; }
        public string UJMPMMFG { get; set; }
        public decimal UJMPSTARTUPCOST { get; set; }
        public decimal UJMPPERCENTAGEOFLIST { get; set; }
        public decimal UJMPSELLPRICE { get; set; }
        public decimal UJMPREPCOMMPERCENTAGE { get; set; }
        public decimal UJMPREPCOMMAMOUNT { get; set; }
        public string UJMPMARGIN { get; set; }
        public string UJMPENDUSERID { get; set; }
        public decimal UJMPLISTPRICE { get; set; }
        public Nullable<System.DateTime> UJMPCUSTOMERAPPROVALDATE { get; set; }
        public string UJMPINPUTSIZE { get; set; }
        public string UJMPJOBNEEDS { get; set; }
        public string UJMPMATL { get; set; }
        public string UJMPMENC { get; set; }
        public string UJMPMFRAME { get; set; }
        public string UJMPSPEC { get; set; }
        public string UJMPQMIN { get; set; }
        public string UJMPQAVG { get; set; }
        public string UJMPQMAX { get; set; }
        public string UJMPOUTPUTSIZE { get; set; }
        public string UJMPMSPECIAL { get; set; }
        public string UJMPRESELLERID { get; set; }
        public string UJMPCONSULTANTID { get; set; }
        public decimal UJMPCOST { get; set; }
        public decimal UJMPQUANTITY { get; set; }
        public decimal UJMPNET { get; set; }
        public string UJMPINDUSTRYTYPEID { get; set; }
        public string UJMPMHP { get; set; }
        public string jmpPartLongDescriptionRTF { get; set; }
        public string jmpPartLongDescriptionText { get; set; }
        public string jmpProductionNotesRTF { get; set; }
        public string jmpProductionNotesText { get; set; }
        public string jmpDocuments { get; set; }
        public string UJMPMHERTZ { get; set; }
        public string UJMPMVOLTS { get; set; }
        public string UJMPMRPM { get; set; }
        public Nullable<System.DateTime> UJMPJOBSTARTUPDATE { get; set; }
        public string UJMPLOCATIONID { get; set; }
        public string UJMPCONTACTID { get; set; }
        public string UJMPENGSTAT { get; set; }
        public Nullable<System.DateTime> UJMPOMSENTDATE { get; set; }
        public string UJMPREDUCER_MFR_MODEL { get; set; }
        public string UJMPRATIO { get; set; }
        public string jmpShipOrganizationID { get; set; }
        public string jmpShipLocationID { get; set; }
        public decimal jmpPartForecastYearID { get; set; }
        public decimal jmpPartForecastPeriodID { get; set; }
        public decimal UJMPCOSTCHECKBYACCOUNTINGDEPT { get; set; }
        public decimal UJMPDISABLE_NOTIFY_NEW_REV { get; set; }
        public string UJMPSERIALNUMBER { get; set; }
    }
}
