//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationLocations
    {
        public string cmlOrganizationID { get; set; }
        public string cmlLocationID { get; set; }
        public string cmlFinanceOrganizationID { get; set; }
        public string cmlName { get; set; }
        public string cmlAddressLine1 { get; set; }
        public string cmlAddressLine2 { get; set; }
        public string cmlAddressLine3 { get; set; }
        public string cmlCity { get; set; }
        public string cmlCounty { get; set; }
        public string cmlState { get; set; }
        public string cmlPostCode { get; set; }
        public string cmlCountry { get; set; }
        public string cmlPhoneNumber { get; set; }
        public string cmlAlternatePhoneNumber { get; set; }
        public string cmlFaxNumber { get; set; }
        public decimal cmlQuoteLocation { get; set; }
        public string cmlQuoteContactID { get; set; }
        public decimal cmlShipLocation { get; set; }
        public string cmlShipContactID { get; set; }
        public decimal cmlARInvoiceLocation { get; set; }
        public string cmlARInvoiceContactID { get; set; }
        public decimal cmlPurchaseLocation { get; set; }
        public string cmlPurchaseContactID { get; set; }
        public decimal cmlAPInvoiceLocation { get; set; }
        public string cmlAPInvoiceContactID { get; set; }
        public decimal cmlCustomerTaxable { get; set; }
        public string cmlCustomerTaxCodeID { get; set; }
        public string cmlCustomerSecondTaxCodeID { get; set; }
        public string cmlCustomerShippingMethodID { get; set; }
        public string cmlCustomerShipPaymentTypeID { get; set; }
        public string cmlTaxExemptNumber { get; set; }
        public string cmlNonTaxReasonID { get; set; }
        public string cmlCustomerPaymentTermID { get; set; }
        public string cmlCurrencyRateID { get; set; }
        public decimal cmlARInvoicePerShipmentLine { get; set; }
        public string cmlSupplierPaymentTermID { get; set; }
        public string cmlSupplierShippingMethodID { get; set; }
        public decimal cmlInactive { get; set; }
        public Nullable<System.DateTime> cmlInactiveDate { get; set; }
        public string cmlUPSAcctNumber { get; set; }
        public string cmlUPSBillingOption { get; set; }
        public decimal cmlResidentialAddress { get; set; }
        public decimal cmlCreditCheckForLocation { get; set; }
        public decimal cmlCustomerCreditLimit { get; set; }
        public decimal cmlCreditHold { get; set; }
        public decimal cmlDirectPayment { get; set; }
        public string cmlBankInitials { get; set; }
        public string cmlBSBNumber { get; set; }
        public string cmlBankAccountName { get; set; }
        public string cmlBankAccountNumber { get; set; }
        public string cmlEFTDescription { get; set; }
        public string cmlBankAccountType { get; set; }
        public string cmlCreatedBy { get; set; }
        public Nullable<System.DateTime> cmlCreatedDate { get; set; }
        public System.Guid cmlUniqueID { get; set; }
        public string cmlEMailAddress { get; set; }
        public string UCMLTELEXT { get; set; }
        public string cmlCountryCode { get; set; }
        public string cmlHDAttachmentFilePath { get; set; }
        public string cmlFreeOnBoardDescription { get; set; }
        public string cmlUPS3rdPartyOrganizationID { get; set; }
        public string cmlUPS3rdPartyLocationID { get; set; }
        public decimal UCMLSTANDARDIZED_FLAG { get; set; }
        public decimal UCMLEMAIL_BAD_FLAG { get; set; }
        public string cmlEFTCode { get; set; }
        public string cmlEFTParticulars { get; set; }
        public string UCMLSHIPCONFIRMATIONEMAIL { get; set; }
        public decimal UCMLSALESTOTAL { get; set; }
        public string UCMLSALESEMPLOYEEID { get; set; }
    }
}
