//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartRevisions
    {
        public string imrPartID { get; set; }
        public string imrPartRevisionID { get; set; }
        public string imrShortDescription { get; set; }
        public string imrUniversalProductCode { get; set; }
        public Nullable<System.DateTime> imrEffectiveStartDate { get; set; }
        public Nullable<System.DateTime> imrEffectiveEndDate { get; set; }
        public decimal imrWebSuppressWhenSold { get; set; }
        public string imrInventoryUnitOfMeasure { get; set; }
        public string imrPurchaseUnitOfMeasure { get; set; }
        public decimal imrQuantityOnHand { get; set; }
        public decimal imrQuantityAllocated { get; set; }
        public decimal imrQuantityToInspect { get; set; }
        public decimal imrQuantityToReturn { get; set; }
        public decimal imrMinimumQuantity { get; set; }
        public decimal imrMaximumQuantity { get; set; }
        public decimal imrManufacturingLotSize { get; set; }
        public decimal imrAverageLaborCost { get; set; }
        public decimal imrAverageOverheadCost { get; set; }
        public decimal imrAverageMaterialCost { get; set; }
        public decimal imrAverageSubcontractCost { get; set; }
        public decimal imrLastLaborCost { get; set; }
        public decimal imrLastOverheadCost { get; set; }
        public decimal imrLastMaterialCost { get; set; }
        public decimal imrLastSubcontractCost { get; set; }
        public decimal imrStandardLaborCost { get; set; }
        public decimal imrStandardOverheadCost { get; set; }
        public decimal imrStandardMaterialCost { get; set; }
        public decimal imrStandardSubcontractCost { get; set; }
        public decimal imrLeadTime { get; set; }
        public decimal imrConversionFactor { get; set; }
        public decimal imrConfigured { get; set; }
        public string imrSupplierOrganizationID { get; set; }
        public string imrPurchaseLocationID { get; set; }
        public decimal imrPreferredRefExists { get; set; }
        public string imrSourceMethodID { get; set; }
        public string imrSourceRevisionID { get; set; }
        public decimal imrInactive { get; set; }
        public string imrPartImageFileName { get; set; }
        public Nullable<System.DateTime> imrLastReceiptDate { get; set; }
        public string imrFormID { get; set; }
        public decimal imrRequiresInspection { get; set; }
        public decimal imrSheetSizeX { get; set; }
        public decimal imrSheetSizeY { get; set; }
        public decimal imrBarLength { get; set; }
        public decimal imrWeight { get; set; }
        public decimal imrWebConfigMode { get; set; }
        public decimal imrWebConfigPriceRule { get; set; }
        public string imrFdxPackaging { get; set; }
        public int imrFdxPackageLength { get; set; }
        public int imrFdxPackageWidth { get; set; }
        public int imrFdxPackageHeight { get; set; }
        public decimal imrFdxHandlingCost { get; set; }
        public decimal imrFdxPackagingCost { get; set; }
        public decimal imrFdxShipCostMarkupPct { get; set; }
        public decimal imrFdxOneItemPerShipment { get; set; }
        public decimal imrFdxNonstandardContainer { get; set; }
        public decimal imrWebShowToPartOrgRef { get; set; }
        public string imrCreatedBy { get; set; }
        public Nullable<System.DateTime> imrCreatedDate { get; set; }
        public System.Guid imrUniqueID { get; set; }
        public decimal imrQuantityOnOrderPurchases { get; set; }
        public decimal imrQuantityOnOrderSales { get; set; }
        public string UIMRMATERIALOFCONSTRUCTION { get; set; }
        public string UIMRITEMNO { get; set; }
        public string UIMRMODEL { get; set; }
        public Nullable<System.DateTime> UIMRSTDMATERIALCOSTDATE { get; set; }
        public string imrLongDescriptionRTF { get; set; }
        public string imrLongDescriptionText { get; set; }
        public string imrLongDescriptionHTML { get; set; }
        public string imrProductionNotesRTF { get; set; }
        public string imrProductionNotesText { get; set; }
        public string imrDocuments { get; set; }
        public string imrInspectionNotesText { get; set; }
        public string imrInspectionNotesRTF { get; set; }
        public string UIMRQUOTETEXTTEXT { get; set; }
        public string UIMRQUOTETEXTRTF { get; set; }
        public decimal imrUseQuotePrice { get; set; }
        public decimal imrPurchaseableItem { get; set; }
        public decimal imrWebSellableToAll { get; set; }
        public string UIMRMATLXX { get; set; }
        public string UIMROUTPUTSIZEXX { get; set; }
        public string UIMRQMINXX { get; set; }
        public string UIMRQAVGXX { get; set; }
        public string UIMRQMAXXX { get; set; }
        public string UIMRJOBNEEDSXX { get; set; }
        public string UIMRSPECXX { get; set; }
        public string UIMRMVOLTSXX { get; set; }
        public string UIMRMHPXX { get; set; }
        public string UIMRMSPECIALXX { get; set; }
        public string UIMRMFRAMEXX { get; set; }
        public string UIMRMENCXX { get; set; }
        public string UIMRMPHASEXX { get; set; }
        public string UIMRMHERTZXX { get; set; }
        public string UIMRMRPMXX { get; set; }
        public string UIMRMMFGXX { get; set; }
        public decimal imrStandardDutyCost { get; set; }
        public decimal imrStandardFreightCost { get; set; }
        public decimal imrStandardMiscCost { get; set; }
        public decimal imrAverageDutyCost { get; set; }
        public decimal imrAverageFreightCost { get; set; }
        public decimal imrAverageMiscCost { get; set; }
        public decimal imrLastDutyCost { get; set; }
        public decimal imrLastFreightCost { get; set; }
        public decimal imrLastMiscCost { get; set; }
        public string imrTariffID { get; set; }
        public decimal imrVolume { get; set; }
        public string UIMRINPUTSIZEXX { get; set; }
        public decimal imrSuppressShortDescription { get; set; }
        public Nullable<System.DateTime> UIMRREORDER_QUEUE_DATE { get; set; }
        public decimal UIMRQUICKSHIP { get; set; }
        public string UIMRBINSHELFNUMBER { get; set; }
        public decimal UIMRSHOPHRS { get; set; }
        public decimal UIMRYEARUSAGEQTY { get; set; }
    }
}
