//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderJobLinks
    {
        public string omjSalesOrderID { get; set; }
        public decimal omjSalesOrderLineID { get; set; }
        public decimal omjSalesOrderJobLinkID { get; set; }
        public decimal omjLinkType { get; set; }
        public decimal omjSalesOrderDeliveryID { get; set; }
        public string omjJobID { get; set; }
        public decimal omjClosed { get; set; }
        public string omjCreatedBy { get; set; }
        public Nullable<System.DateTime> omjCreatedDate { get; set; }
        public System.Guid omjUniqueID { get; set; }
    }
}
